name: Build and Deploy

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  push:
    branches:
      - 'pr-*'
    paths-ignore:
      - '**.md'
  workflow_dispatch:
    inputs:
      username:
        description: 'Username'
        required: true
        type: choice
        options:
          - avery

concurrency:
  group: ${{ github.event_name }}-${{ github.ref_name || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  pull-requests: write
  checks: write
  issues: write
  deployments: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate change log
        id: changelog
        run: |
          CHANGES=$(git log $(git describe --tags --abbrev=0 2>/dev/null || echo HEAD~10)..HEAD --pretty=format:"- %s" | grep -v "Merge")
          echo "CHANGES<<EOF" >> $GITHUB_ENV
          echo "$CHANGES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Set tag based on context
        id: set-tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "TAG=${{ github.ref_name }}-${{ github.event.inputs.username }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "TAG=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TAG=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" =~ ^pr- ]]; then
            echo "TAG=${{ github.ref_name }}-${{ github.run_number }}" >> $GITHUB_ENV
          else
            echo "TAG=build-${{ github.run_number }}" >> $GITHUB_ENV
          fi

      - name: Build app
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: .output
          include-hidden-files: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .output

      - name: Set deployment target
        id: deployment-target
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "CHANNEL=live" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "CHANNEL=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" =~ ^pr- ]]; then
            PR_NUM=$(echo "${{ github.ref_name }}" | sed 's/pr-//')
            echo "CHANNEL=pr-$PR_NUM-preview" >> $GITHUB_ENV
          else
            echo "CHANNEL=default-${{ github.run_number }}" >> $GITHUB_ENV
          fi

      - name: Deploy to Firebase Hosting
        id: deploy-firebase
        uses: FirebaseExtended/action-hosting-deploy@v0.9.0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          projectId: 'avery-shedden-me'
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AVERY_SHEDDEN_ME }}
          channelId: ${{ env.CHANNEL }}

  version-bump:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Bump version
        run: |
          npm version patch -m "Bump version to %s [skip ci]"
          git push
          git push --tags
