name: build-and-deploy-pipeline

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - preview
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:
    inputs:
      choice:
        description: 'Who is the author of this workflow?'
        required: true
        type: choice
        options:
          - Avery Shedden
          - Avery Shedden (GitHub Actions)
        default: Avery Shedden

jobs:
  extract-metadata:
    runs-on: ubuntu-latest
    outputs:
      author: ${{ steps.get-author.outputs.author }}
    steps:
      - name: Get PR author
        if: github.event_name == 'pull_request'
        id: get-author-pr
        run: echo "author=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT

      - name: Get push author
        if: github.event_name == 'push'
        id: get-author-push
        run: echo "author=${{ github.actor }}" >> $GITHUB_OUTPUT

      - name: Set author
        id: get-author
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
              echo "author=${{ steps.get-author-pr.outputs.author }}" >> $GITHUB_OUTPUT
          else
              echo "author=${{ steps.get-author-push.outputs.author }}" >> $GITHUB_OUTPUT
          fi
  build:
    uses: ./.github/workflows/reusable-build-step.yml
    with:
      nodejs-version: '20' # LTS version
      caller_workflow: ${{ github.workflow }}

  deploy:
    needs: build
    if: github.event.pull_request.merged == true || github.ref == 'refs/heads/preview'
    uses: ./.github/workflows/reusable-firebase-hosting-deploy.yml
    with:
      site: 'avery-shedden-me'
      env: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
      channel_id: ${{ github.ref == 'refs/heads/main' && 'live' || github.ref_name }}
      working_directory: '.'
      caller_workflow: ${{ github.workflow }}
      artifacts_prefix: 'build-output'
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AVERY_SHEDDEN_ME }}
