name: Bump minor version

on:
  workflow_call:

jobs:
  bump_version:
    outputs:
      version: ${{ steps.bump_version.outputs.version }}
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Set local git user
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "${{ github.event.sender.login }}@users.noreply.github.com"
      - name: Bump version
        id: bump_version
        run: |
          echo "current_version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
          echo "new_version=$(npm version patch)" >> $GITHUB_OUTPUT
      - name: Push changes
        if: ${{ steps.bump_version.outputs.new_version != '' }}
        run: |
          git add package.json package-lock.json
          git commit -m "Bump version to ${{ steps.bump_version.outputs.new_version }}"
          git tag -a "${{ steps.bump_version.outputs.new_version }}" -m "Version bumped from v${{ steps.bump_version.outputs.current_version }} > ${{ steps.bump_version.outputs.new_version }}"
          git pull --rebase
          git push
