name: Bump minor version

on:
  workflow_call:

jobs:
  bump_version:
    outputs:
      version: ${{ steps.bump_version.outputs.version }}
    name: bump version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Set local git user
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "${{ github.event.sender.login }}@users.noreply.github.com"
      - name: Bump version
        id: bump_version
        run: |
          echo "current_version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
          echo "new_version=$(npm version patch --no-git-tag-version --allow-same-version)" >> $GITHUB_OUTPUT
      - name: Add, Commit, Tag and push changes
        if: ${{ steps.bump_version.outputs.new_version != '' }}
        run: |
          if [ git rev-parse --verify refs/tags/${{ steps.bump_version.outputs.new_version }} ]; then
            echo "Tag already exists for version ${{ steps.bump_version.outputs.new_version }}. Bumping version again."
            echo "new_new_version=$(npm version patch --no-git-tag-version --allow-same-version)"
            exit 0
          fi
          echo "Bumping version from ${{ steps.bump_version.outputs.current_version }} to ${new_new_version}"
          git add package.json package-lock.json
          git commit -m "Bump version to ${new_new_version || ${{ steps.bump_version.outputs.new_version }}}"
          git tag -a "${new_new_version}" -m "Version bumped from v${{ steps.bump_version.outputs.current_version }} > ${new_new_version || ${{ steps.bump_version.outputs.new_version }}}"
          git push --tags
