name: Deploy to Firebase Hosting on PR
on:
  pull_request:
  workflow_dispatch:
    inputs:
      channelId:
        type: choice
        description: Which channel to deploy to
        options:
          - live
          - preview
      name:
        type: choice
        description: Who is running this
        options:
          - avery

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install && echo 'Install Done 👌' && npm run build && echo 'Build Done 👌'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AVERY_SHEDDEN_ME }}
          projectId: ${{ inputs.projectId || 'avery-shedden-me' }}
          channelId: ${{ inputs.channelId || 'live' }}
