name: Manual Deploy to Firebase Hosting

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who is running this
        options:
          - avery
      channelId:
        type: choice
        description: Which channel to deploy to
        options:
          - live
          - preview
jobs:
  call_build_and_preview:
    uses: ./.github/workflows/firebase-hosting-pull-request.yml
    with:
      channelId: ${{ github.event.inputs.channelId }}
      projectId: 'avery-shedden-me'
    secrets: inherit
