name: Manual Build and Deploy

on:
  workflow_dispatch:
    inputs:
      author:
        type: choice
        description: 'Who is running this deployment?'
        required: true
        options:
          - avery
          - automated

jobs:
  trigger_pipeline:
    name: Trigger Build and Deploy Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build and Deploy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-and-deploy.yml
          inputs: |
            {
              "caller_workflow": "manual-deploy"
            }
          token: ${{ secrets.GITHUB_TOKEN }}
