name: Manual workflow run

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who is running this
        options:
          - avery
      chanelId:
        type: choice
        description: Which channel to deploy to
        options:
          - live
          - preview
jobs:
  call_build_and_deploy:
    uses: ./.github/workflows/firebase-hosting-pull-request.yml
    with:
      channelId: ${{ github.event.inputs.chanelId }}
      projectId: 'avery-shedden-me'
    secrets: inherit
