name: Reusable Build Step

on:
  workflow_call:
    inputs:
      caller_workflow:
        required: true
        type: string
      nodejs-version:
        required: true
        type: string
      artifacts_name:
        required: true
        type: string
      working_directory:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: write
    outputs:
      build_id: ${{ github.run_id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.nodejs-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        env:
          CI: true

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifacts_name }}
          path: .output
          include-hidden-files: true
          retention-days: 1
