name: Reusable Deploy Workflow
description: Reusable workflow for deploying to Firebase Hosting

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      channel_id:
        required: true
        type: string
      working_directory:
        required: true
        type: string
      caller_workflow:
        required: true
        type: string
      artifacts_name:
        required: true
        type: string
      site:
        required: true
        type: string
    secrets:
      FIREBASE_SERVICE_ACCOUNT:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifacts_name }}
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{ inputs.site }}
          channelId: ${{ inputs.channel_id }}
          target: ${{ inputs.site }}
