name: Build, Test and Deploy to GitHub Pages

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

on:
  push:
    branches: ["main"]
    tags-ignore:
      - "v*"

jobs:
  call_build_workflow:
    name: Build Static Site
    uses: beancow/avery-shedden-me/.github/workflows/build-static-site.yml@main
    secrets: inherit
    with:
      base_path: ${{ github.event.repository.name }}
  call_test_workflow:
    name: Run Unit Tests
    needs: [call_build_workflow]
    if: ${{ needs.call_build_workflow.result == 'success' }}
    uses: beancow/avery-shedden-me/.github/workflows/run-unit-tests.yml@main
    secrets: inherit
  call_deploy_workflow:
    name: Deploy to GitHub Pages
    needs: [call_test_workflow, call_build_workflow]
    if: ${{ needs.call_test_workflow.result == 'success' && needs.call_build_workflow.result == 'success' }}
    uses: beancow/avery-shedden-me/.github/workflows/deploy-gh-pages.yml@main
    secrets: inherit
  call_bump_version_workflow:
    name: Bump minor version
    needs: [call_deploy_workflow]
    if: ${{ needs.call_deploy_workflow.result == 'success' }}
    uses: beancow/avery-shedden-me/.github/workflows/bump-version.yml@main
    secrets: inherit
